version: "3"
services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-intermediate-day2-fluentd
    user: fluent
    tty: true
    volumes:
      - $PROJECT_HOME/fluent.conf:/fluentd/etc/fluent.conf
      - $PROJECT_HOME/source:/fluentd/source
      - $PROJECT_HOME/target:/fluentd/target
